# Generated by Django 5.2.4 on 2025-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, default='/Course Management Backend/media/Course/Default_Course.jpg', null=True, upload_to='Course Management Backend/media/Course'),
        ),
    ]
