# Generated by Django 5.2.4 on 2025-07-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='category_id',
        ),
    ]
